#In production server, for overriding this profiles config, gragle should run with : bootRun -Dspring.profiles.active=production
spring:
  profiles:
    active: development
#  main:
#    banner-mode: 'off'
banner:
  location: 'classpath:banner.txt'
#Config for shell-remote
#TODO : Disable spring-boot banner when login shell
shell:
  ssh:
    port: 2000
#  command-path-patterns: 'classpath*:/commands/**'
#Production env config

#spring.data.cassandra.port=9042
#spring.data.cassandra.keyspace-name=mykeyspace
#spring.data.cassandra.contact-points=192.168.56.101

---
spring:
  profiles: produciton
  data:
      cassandra:
        port: 9042
        keyspace-name: mykeyspace
        contact-points: 192.168.56.101
server:
  address: localhost
#Logging configure
logging:
  config: 'classpath:log4j2.yaml'

#Development env config
---
spring:
  profiles: development
  data:
    cassandra:
      port: 9042
      keyspace-name: mykeyspace
      contact-points: 192.168.56.101
security:
  user:
    name: namvu
    password: namvu
server:
  address: localhost
#Logging configure
logging:
  config: 'classpath:log4j2_dev.yaml'
  level:
    'org.springframework': INFO